AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
Description: ""
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "deglue1"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        -
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
          BucketKeyEnabled: true
      OwnershipControls:
        Rules:
        -
          ObjectOwnership: "BucketOwnerEnforced"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  GlueJob:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "deglue-job"
      Description: ""
      Role: !GetAtt IAMRole.Arn
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/scripts/deglue-job.py"
        PythonVersion: "3"
      DefaultArguments:
        --enable-metrics: "true"
        --enable-spark-ui: "true"
        --spark-event-logs-path: !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/sparkHistoryLogs/"
        --enable-job-insights: "false"
        --enable-observability-metrics: "true"
        --enable-glue-datacatalog: "true"
        --job-bookmark-option: "job-bookmark-disable"
        --job-language: "python"
        --TempDir: !Sub "s3://aws-glue-assets-${AWS::AccountId}-${AWS::Region}/temporary/"
        --enable-auto-scaling: "true"
      MaxRetries: 0
      AllocatedCapacity: 2
      Timeout: 10
      GlueVersion: "5.0"
      MaxCapacity: 2
      NumberOfWorkers: 2
      WorkerType: "G.1X"

  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/service-role/"
      RoleName: "AWSGlueServiceRole-deglue"
      AssumeRolePolicyDocument: !Sub "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"glue.amazonaws.com\"},\"Action\":\"sts:AssumeRole\",\"Condition\":{\"StringEquals\":{\"aws:SourceAccount\":\"${AWS::AccountId}\"}}},{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"glue.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns:
      - !Ref IAMManagedPolicy
      - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
      - "arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess"
      - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceNotebookRole"

  IAMManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: "AWSGlueServiceRole-deglue-EZCRC-s3Policy"
      Path: "/service-role/"
      PolicyDocument: !Sub |
          {
          	"Version": "2012-10-17",
          	"Statement": [
          		{
          			"Effect": "Allow",
          			"Action": [
          				"s3:GetObject",
          				"s3:PutObject",
          				"s3:DeleteObject"
          			],
          			"Resource": [
          				"arn:aws:s3:::${S3Bucket}/*"
          			],
          			"Condition": {
          				"StringEquals": {
          					"aws:ResourceAccount": "${AWS::AccountId}"
          				}
          			}
          		}
          	]
          }

